let dishes = [
  {
    name: "Gebratene Nudeln mit Hähnchen",
    ingredient: [
      "Eiernudeln",
      "Hähnchenbrust",
      "Sojasoße",
      "Karotten",
      "Zucchini",
      "Zwiebeln",
      "Sesamöl",
    ],
    price: 9.5,
  },
  {
    name: "Rotes Thai-Curry mit Gemüse",
    ingredient: [
      "Kokosmilch",
      "rote Currypaste",
      "Zucchini",
      "Paprika",
      "Karotten",
      "Bambussprossen",
      "Jasminreis",
    ],
    price: 10.2,
  },
  {
    name: "Sushi-Set Maki Mix",
    ingredient: [
      "Lachs",
      "Gurke",
      "Avocado",
      "Nori-Blätter",
      "Sushi-Reis",
      "Reisessig",
      "Sojasoße",
      "Wasabi",
    ],
    price: 12.8,
  },
  {
    name: "Gebratener Reis mit Ei und Gemüse",
    ingredient: [
      "Reis",
      "Ei",
      "Erbsen",
      "Karotten",
      "Sojasoße",
      "Sesamöl",
      "Frühlingszwiebeln",
    ],
    price: 8.9,
  },
  {
    name: "Gemüse-Curry mit Kokosmilch",
    ingredient: [
      "Süßkartoffeln",
      "Zucchini",
      "Karotten",
      "Kokosmilch",
      "Currypaste",
      "Reis",
      "Koriander",
    ],
    price: 8.7,
  },
  {
    name: "Rindfleisch mit schwarzer Pfeffersoße",
    ingredient: [
      "Rindfleisch",
      "Sojasoße",
      "Austernsoße",
      "Zwiebeln",
      "Paprika",
      "Knoblauch",
      "Jasminreis",
    ],
    price: 11.5,
  },
];
