let dishes = [
  {
    name: "Gebratene Nudeln mit Hähnchen",
    ingredient: [
      "Eiernudeln",
      "Hähnchenbrust",
      "Sojasoße",
      "Karotten",
      "Zucchini",
      "Zwiebeln",
      "Sesamöl",
    ],
    dishesPrice: 9.5,
  },
  {
    name: "Rotes Thai-Curry mit Gemüse",
    ingredient: [
      "Kokosmilch",
      "rote Currypaste",
      "Zucchini",
      "Paprika",
      "Karotten",
      "Bambussprossen",
      "Jasminreis",
    ],
    dishesPrice: 10.2,
  },
  {
    name: "Sushi-Set Maki Mix",
    ingredient: [
      "Lachs",
      "Gurke",
      "Avocado",
      "Nori-Blätter",
      "Sushi-Reis",
      "Reisessig",
      "Sojasoße",
      "Wasabi",
    ],
    dishesPrice: 12.8,
  },
  {
    name: "Gebratener Reis mit Ei und Gemüse",
    ingredient: [
      "Reis",
      "Ei",
      "Erbsen",
      "Karotten",
      "Sojasoße",
      "Sesamöl",
      "Frühlingszwiebeln",
    ],
    dishesPrice: 8.9,
  },
  {
    name: "Gemüse-Curry mit Kokosmilch",
    ingredient: [
      "Süßkartoffeln",
      "Zucchini",
      "Karotten",
      "Kokosmilch",
      "Currypaste",
      "Reis",
      "Koriander",
    ],
    dishesPrice: 8.7,
  },
  {
    name: "Rindfleisch mit schwarzer Pfeffersoße",
    ingredient: [
      "Rindfleisch",
      "Sojasoße",
      "Austernsoße",
      "Zwiebeln",
      "Paprika",
      "Knoblauch",
      "Jasminreis",
    ],
    dishesPrice: 11.5,
  },
  {
    name: "Pad Thai mit Garnelen",
    ingredient: [
      "Reisnudeln",
      "Garnelen",
      "Erdnüsse",
      "Sojasprossen",
      "Ei",
      "Limette",
      "Tamarindensauce",
    ],
    dishesPrice: 11.9,
  },
  {
    name: "Teriyaki-Lachs mit Gemüse",
    ingredient: [
      "Lachsfilet",
      "Teriyaki-Soße",
      "Brokkoli",
      "Karotten",
      "Sesam",
      "Jasminreis",
    ],
    dishesPrice: 13.5,
  },
  {
    name: "Pho Bo – Vietnamesische Rindersuppe",
    ingredient: [
      "Rinderbrühe",
      "Reisbandnudeln",
      "Rindfleisch",
      "Koriander",
      "Frühlingszwiebeln",
      "Limette",
    ],
    dishesPrice: 10.8,
  },
  {
    name: "Gyoza – Japanische Teigtaschen mit Gemüsefüllung",
    ingredient: [
      "Weizenteig",
      "Kohl",
      "Karotten",
      "Ingwer",
      "Knoblauch",
      "Sojasoße",
    ],
    dishesPrice: 7.9,
  },
  {
    name: "Miso-Ramen mit Ei",
    ingredient: [
      "Ramen-Nudeln",
      "Miso-Brühe",
      "Ei",
      "Frühlingszwiebeln",
      "Mais",
      "Nori",
      "Sojasprossen",
    ],
    dishesPrice: 10.9,
  },
  {
    name: "Hähnchen-Saté mit Erdnusssoße",
    ingredient: [
      "Hähnchenspieße",
      "Erdnusssoße",
      "Kokosmilch",
      "Kurkuma",
      "Reis",
    ],
    dishesPrice: 9.8,
  },
  {
    name: "Gebratene Udon-Nudeln mit Rindfleisch",
    ingredient: [
      "Udon-Nudeln",
      "Rindfleisch",
      "Zwiebeln",
      "Sojasoße",
      "Knoblauch",
      "Sesamöl",
    ],
    dishesPrice: 10.5,
  },
  {
    name: "Scharfes Kimchi-Reisgericht",
    ingredient: [
      "Reis",
      "Kimchi",
      "Ei",
      "Frühlingszwiebeln",
      "Chilipaste",
      "Sojasoße",
    ],
    dishesPrice: 9.2,
  },
  {
    name: "Tofu-Gemüse-Wok",
    ingredient: [
      "Tofu",
      "Brokkoli",
      "Zucchini",
      "Paprika",
      "Sojasoße",
      "Ingwer",
      "Reis",
    ],
    dishesPrice: 8.9,
  },
  {
    name: "Mango Sticky Rice",
    ingredient: ["Klebreis", "Kokosmilch", "Mango", "Zucker", "Sesam"],
    dishesPrice: 6.5,
  },
];
